### ISSUE TITLE
Minecraft server - command() never returns

### ISSUE THREAD

**Issue by kubastick** [Hexer10/source_query_rcon#3]
After executing `command()`function when connected to a minecraft server, it never returns result.
Despite this, the command is executed correctly on the server.

**Comment by Hexer10** [comment]
Sorry for the late answer, I just noticed this issue...
Tbh this packages was meant only to work with SourceGames like CSGO or CSS, but I could try to extend it to other games like Minecraft.

**Comment by Hexer10** [comment]
If anyone still interested in the latest commit https://github.com/Hexer10/source_query_rcon/commit/4fdea5d70d51918f08a7a4b0d7760e542d814f0b I've added support the the Rcon protocol in Minecraft, Query is not yet supported.

**Comment by Hexer10** [comment]
-
